name: Post-Deploy Tasks

on:
  deployment_status:
  workflow_dispatch:


jobs:
  post-deplay-tasks:
    if: ${{ github.event.deployment_status.state == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Get LAST modified time of nfl_roster.json
        run: |
          curl --fail --silent --show-error "${{ secrets.RAILWAY_BACKEND_URL }}/nfl/roster/meta"

      - name: Refresh deployed nfl_roster.json
        run: |
          curl --fail --silent --show-error "${{ secrets.RAILWAY_BACKEND_URL }}/nfl/athletes"
        
      - name: Get NEW modified time of nfl_roster.json
        run: |
          curl --fail --silent --show-error "${{ secrets.RAILWAY_BACKEND_URL }}/nfl/roster/meta"